import { Appointment, Patient, MedicalRecord } from './types';

const today = new Date();
const fmt = (d: Date) => d.toISOString().split('T')[0];
const d = (offset: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() + offset);
  return fmt(date);
};

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'p1',
    fullName: 'Anna Silva Santos',
    cpf: '123.456.789-00',
    sex: 'female',
    birthDate: '1989-07-10',
    profession: 'Teacher',
    email: 'anna.silva@email.com',
    phone: '+55 85 98905-2788',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'p2',
    fullName: 'Carlos Menezes Jr.',
    cpf: '987.654.321-00',
    sex: 'male',
    birthDate: '1985-03-22',
    profession: 'Engineer',
    phone: '+55 85 99123-4567',
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'p3',
    fullName: 'Maria Fernanda Carneiro',
    sex: 'female',
    birthDate: '1992-11-05',
    phone: '+55 85 98800-1234',
    createdAt: '2026-02-10T14:00:00Z',
  },
  {
    id: 'p4',
    fullName: 'Douglas Fontenele Ortega',
    sex: 'male',
    birthDate: '1990-06-18',
    createdAt: '2026-03-01T11:00:00Z',
  },
  {
    id: 'p5',
    fullName: 'Isabelle Gurgel e Silva',
    sex: 'female',
    birthDate: '1995-09-14',
    phone: '+55 85 99754-1812',
    createdAt: '2026-03-15T09:30:00Z',
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'a1',
    patientId: 'p1',
    patientName: 'Anna Silva Santos',
    date: d(0),
    startTime: '09:00',
    endTime: '10:00',
    durationMinutes: 60,
    type: 'in-person',
    consultationType: '1st Consultation - Adult',
    paymentType: 'private',
    paymentAmount: 350,
    paymentStatus: 'pending',
    status: 'confirmed',
    professionalId: 'prof1',
  },
  {
    id: 'a2',
    patientId: 'p2',
    patientName: 'Carlos Menezes Jr.',
    date: d(0),
    startTime: '10:30',
    endTime: '11:30',
    durationMinutes: 60,
    type: 'online',
    consultationType: 'Follow-up Consultation - Adult',
    paymentType: 'private',
    paymentAmount: 300,
    paymentStatus: 'paid',
    status: 'confirmed',
    professionalId: 'prof1',
  },
  {
    id: 'a3',
    patientId: 'p3',
    patientName: 'Maria Fernanda Carneiro',
    date: d(0),
    startTime: '14:00',
    endTime: '15:00',
    durationMinutes: 60,
    type: 'in-person',
    consultationType: 'Follow-up Consultation - Adult',
    paymentType: 'private',
    paymentAmount: 300,
    paymentStatus: 'pending',
    status: 'confirmed',
    professionalId: 'prof1',
  },
  {
    id: 'a4',
    patientId: '',
    patientName: '',
    date: d(0),
    startTime: '16:00',
    endTime: '17:00',
    durationMinutes: 60,
    type: 'online',
    consultationType: '1st Consultation - Adolescent',
    paymentType: 'private',
    paymentAmount: 0,
    paymentStatus: 'pending',
    status: 'blocked',
    professionalId: 'prof1',
  },
  {
    id: 'a5',
    patientId: 'p4',
    patientName: 'Douglas Fontenele Ortega',
    date: d(1),
    startTime: '11:00',
    endTime: '12:00',
    durationMinutes: 60,
    type: 'in-person',
    consultationType: '1st Consultation - Adult',
    paymentType: 'private',
    paymentAmount: 350,
    paymentStatus: 'pending',
    status: 'scheduled',
    professionalId: 'prof1',
  },
  {
    id: 'a6',
    patientId: 'p5',
    patientName: 'Isabelle Gurgel e Silva',
    date: d(2),
    startTime: '10:00',
    endTime: '11:30',
    durationMinutes: 90,
    type: 'in-person',
    consultationType: '1st Consultation - Adult',
    paymentType: 'private',
    paymentAmount: 600,
    paymentStatus: 'paid',
    status: 'completed',
    professionalId: 'prof1',
  },
];

export const MOCK_RECORDS: MedicalRecord[] = [
  {
    id: 'r1',
    patientId: 'p1',
    professionalId: 'prof1',
    date: '2026-05-27',
    time: '09:17',
    content: `IDENTIFICATION:\nAnna, 36 years old, widowed (1 child - 9 years), lives with mother-in-law and son, originally from Fortaleza, evangelical (non-practicing)\n\nIN PSYCHOTHERAPY: yes, started yesterday.\n\nHDA:\nMoved in with mother-in-law after husband's passing, along with brothers-in-law.\n"These people are very different from me."\nDecided to move there to help mother-in-law.\nFeels she took on the responsibility of caring for the mother-in-law that her husband used to fulfil.`,
    createdAt: '2026-05-27T09:17:00Z',
  },
];
